export const ADDTODO = 'todos/addtodo'
export const TOOGLETODO = 'todos/toggletodo'
export const SETCOLORS = 'todos/setcolors'
export const DELETETODO = 'todos/deletetodo'
export const ALLCOMPLETED = 'todos/allcompleted'
export const CLEARCOMPLETD = 'todos/clearcompleted'